dataset_type:
  _target_: datasets.afhq.AFHQDiffusionDataset
  root: /home/quyennd/Data/Datasets/AFHQ/afhq
  train: False
transforms:
  - _target_: albumentations.Resize
    height: 256
    width: 256
  - _target_: albumentations.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    max_pixel_value: 255.0
  - _target_: albumentations.pytorch.ToTensorV2